require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
# pod 'Firebase/Core'
# pod 'Firebase/MLVision'
# pod 'Firebase/MLVisionBarcodeModel' 

target 'transportApp' do
  
  permissions_path = '../node_modules/react-native-permissions/ios'

  config = use_native_modules!
  
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
 
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
   
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  pod 'react-native-camera', path: '../node_modules/react-native-camera',subspecs:['BarcodeDetectorMLKit']
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # react-native-maps dependencies
    rn_maps_path = '../node_modules/react-native-maps' # This path is likely to be `../node_modules/react-native-maps` in your own project.

    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod '@darron1217_react-native-background-geolocation', :path => '../node_modules/@darron1217/react-native-background-geolocation'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'transportAppTests' do
    inherit! :complete
	
    # Pods for testing
  end

 # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
